- type: department
  id: Cargo
  description: department-Cargo-description
  color: "#A46106"
  roles:
  - CargoTechnician
  - Quartermaster

- type: department
  id: Civilian
  description: department-Civilian-description
  color: "#9FED58"
  weight: -10
  roles:
  - Chaplain
  - Clown
  - HeadOfPersonnel
  - Lawyer
  - Reporter
  - Visitor

- type: department
  id: Command
  description: department-Command-description
  color: "#334E6D"
  roles:
  - Warden
  - CentralCommandOfficial
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  - Quartermaster
  primary: false
  weight: 100

- type: department
  id: Maintenance
  description: department-Maintenance-description
  color: "#9FED58"
  roles:
  - AtmosphericTechnician
  - ChiefEngineer
  - StationEngineer
  - Borg
  - Janitor

- type: department
  id: Inmate
  description: department-Inmate-description
  color: "#EFB341"
  roles:
  - Prisoner
  - Chef
  - Botanist
  - Librarian

- type: department
  id: Medical
  description: department-Medical-description
  color: "#52B4E9"
  roles:
  - Chemist
  - ChiefMedicalOfficer
  - MedicalDoctor
  - Psychologist

- type: department
  id: Security
  description: department-Security-description
  color: "#DE3A3A"
  weight: 20
  roles:
  - HeadOfSecurity
  - SecurityCadet
  - SecurityOfficer
  - Detective
