- type: job
  id: PrisonLibrarian
  name: job-name-prison-librarian
  description: job-description-prison-librarian
  playTimeTracker: JobPrisonLibrarian
  startingGear: LibrarianGear
  icon: "JobIconLibrarian"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance

- type: startingGear
  id: LibrarianGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    id: LibrarianPDA
    ears: ClothingHeadsetService
    pocket1: d10Dice
    pocket2: HandLabeler # for making named bestsellers
  storage:
    back:
    - BookRandom
